/// <reference types="cypress" />

describe('cat herder app', () => {
  beforeEach(() => {
    // login user
    cy.visit('http://localhost:5173/')
    cy.get('[data-cy="headline"]').contains('Cat Herder')
    cy.get('[data-cy="open-login-btn"]').click()
    cy.get('[data-cy="user-mail-input"]').type(Cypress.env('user_email'))
    cy.get('[data-cy="user-password-input"]').type(Cypress.env('user_password'))
    cy.get('[data-cy="login-button"]').click()
    cy.contains(Cypress.env('user_name'))
  })

  it('can add new cat', () => {
    const catName = 'TestCatto'
    cy.get('[data-cy="add-cat-btn"]').click()
    cy.get('[data-cy="open-avatar-dialog"]').click()
    cy.get('[class=pick-avatar-button]').first().click()
    cy.get('[data-cy="input-cat-name"]').type(catName)
    cy.get('[data-cy="select-sex-dropdown"]').click()
    cy.contains('weiblich').click()
    cy.get('[data-cy="cat-birthday-selection"]').click()
    cy.contains('Jan ').click()
    cy.get('[data-cy="catbreed-selection-dropdown"]').click()
    cy.contains('Kurzhaar-Mischung').click()
    cy.get('[data-cy="indoor-outdoor-selection-dropdown"]').click()
    cy.contains('Wohnungskatze').click()
    cy.get('[data-cy="button-right"]').click()
    cy.get('[data-cy="weight-input"]').type('{leftarrow}{leftarrow}5')
    cy.get('[data-cy="input-food-varieties"]').click()
    cy.contains('Dosenfutter').click()
    cy.contains('Barf').click()
    cy.get('[data-cy="input-food-varieties"]').click()
    cy.get('[data-cy="feeding-times-selection"]').click()
    cy.get('#feeding-selection_2').click()
    cy.get('[data-cy="button-right"]').click()
    cy.get('[data-cy="neutered-dropdown"]').click()
    cy.get('#neutered-selection_0').click()
    cy.get('[data-cy="drug-dropdown"]').click()
    cy.contains('nein').click()
    cy.scrollTo('bottom')
    cy.get('[data-cy="button-right"]').click()
    cy.get('[data-cy="personality-dropdown"]').click()
    cy.contains('freundlich').click()
    cy.get('[data-cy="personality-dropdown"]').click()
    cy.get('[data-cy="playtimes-dropdown"]').click()
    cy.contains('2-3 mal am Tag').click()
    cy.get('[data-cy="save-cat-btn"]').click()
    cy.contains(catName)
  })
})
